# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 18:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BedInfo',
            fields=[
                ('bedId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('ward', models.CharField(max_length=100)),
                ('wardType', models.CharField(max_length=30)),
                ('depid', models.CharField(max_length=30)),
                ('currentUnit', models.CharField(max_length=30, null=True)),
                ('status', models.IntegerField(choices=[(0, 'notbooked'), (1, 'partialbooked'), (2, 'booked')], default='notbooked')),
            ],
        ),
        migrations.CreateModel(
            name='Borrowed_Beds',
            fields=[
                ('borrowingid', models.AutoField(primary_key=True, serialize=False)),
                ('depId', models.CharField(max_length=50, null=True)),
                ('fromUnit', models.CharField(max_length=50)),
                ('toUnit', models.CharField(max_length=50)),
                ('timestamp', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checkup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bedId', models.CharField(max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('condition', models.IntegerField()),
                ('expDischargefromhosp', models.DateField(blank=True, null=True)),
                ('expDischargefromward', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('empId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.CharField(max_length=8, null=True)),
                ('name', models.CharField(max_length=30)),
                ('depid', models.CharField(max_length=30)),
                ('designationid', models.CharField(max_length=30)),
                ('ward', models.CharField(max_length=30, null=True)),
                ('empType', models.CharField(max_length=30, null=True)),
                ('unit', models.CharField(max_length=30)),
                ('responsible', models.IntegerField(choices=[(0, 'not responsible'), (1, 'responsible')], default='not responsible')),
            ],
        ),
        migrations.CreateModel(
            name='General_UnitBedCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('depid', models.CharField(max_length=50)),
                ('threshold', models.IntegerField()),
                ('filledCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='General_WardBedCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ward', models.CharField(max_length=100)),
                ('depid', models.CharField(max_length=50)),
                ('totalCount', models.IntegerField()),
                ('filledCount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('Movementid', models.AutoField(primary_key=True, serialize=False)),
                ('patientId', models.CharField(max_length=30)),
                ('ward', models.CharField(max_length=30)),
                ('wardType', models.CharField(max_length=30)),
                ('inDate', models.DateField(auto_now_add=True)),
                ('outDate', models.DateField(null=True)),
                ('inCondition', models.IntegerField(null=True)),
                ('outCondition', models.IntegerField(null=True)),
                ('inExpectedDaysInWard', models.IntegerField(null=True)),
                ('inExpectedDaysInHospital', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patientId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, null=True)),
                ('age', models.PositiveIntegerField(null=True)),
                ('sex', models.CharField(choices=[('M', 'male'), ('F', 'female')], max_length=2, null=True)),
                ('unit', models.CharField(max_length=30, null=True)),
                ('depid', models.CharField(max_length=30, null=True)),
                ('loc', models.CharField(blank=True, max_length=30, null=True)),
                ('wardType', models.CharField(blank=True, max_length=30, null=True)),
                ('diagnosis', models.CharField(max_length=30, null=True)),
                ('pincode', models.IntegerField(null=True)),
                ('contactNo', models.IntegerField(null=True)),
                ('admitted', models.BooleanField(default=False)),
                ('regDate', models.DateField(null=True)),
                ('expAdmitDate', models.DateField(blank=True, null=True)),
                ('admitDate', models.DateField(blank=True, null=True)),
                ('latestMovementId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bedapp.Movement')),
            ],
        ),
        migrations.CreateModel(
            name='PatientVisit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currCond', models.IntegerField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('expectedAdmitDate', models.DateField()),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedapp.Patient')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('requestid', models.AutoField(primary_key=True, serialize=False)),
                ('issuing_doctor_name', models.CharField(max_length=30)),
                ('patientId', models.CharField(max_length=30)),
                ('patient_name', models.CharField(max_length=30)),
                ('condition', models.IntegerField()),
                ('daysexpected', models.DateField()),
                ('from_resident', models.CharField(max_length=30)),
                ('fromUnit', models.CharField(max_length=30, null=True)),
                ('toUnit', models.CharField(max_length=30, null=True)),
                ('fromWard', models.CharField(max_length=30, null=True)),
                ('toWard', models.CharField(max_length=30)),
                ('fromWardType', models.CharField(max_length=30, null=True)),
                ('toWardType', models.CharField(max_length=30, null=True)),
                ('fromBedId', models.CharField(max_length=30, null=True)),
                ('returnbedId', models.CharField(max_length=30, null=True)),
                ('approval_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Waiting For Borrowing Response')], default=0)),
                ('from_msg', models.CharField(max_length=200, null=True)),
                ('to_msg', models.CharField(max_length=200, null=True)),
                ('requestType', models.IntegerField(choices=[(0, 'IntraUnit'), (1, 'InterUnit')], default=0)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Rollback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patientId', models.CharField(max_length=30)),
                ('fromWard', models.CharField(max_length=30)),
                ('toWard', models.CharField(max_length=30)),
                ('fromWardType', models.CharField(max_length=30)),
                ('toWardType', models.CharField(max_length=30)),
                ('fromBedId', models.CharField(max_length=30, null=True)),
                ('toBedId', models.CharField(max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('fromUnit', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Special_UnitCount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(max_length=100)),
                ('ward', models.CharField(max_length=100)),
                ('filledCount', models.IntegerField()),
                ('totalCount', models.IntegerField()),
                ('depid', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TransferTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('fromUnit', models.CharField(max_length=30, null=True)),
                ('fromWard', models.CharField(max_length=30, null=True)),
                ('toWard', models.CharField(max_length=30)),
                ('fromWardType', models.CharField(max_length=30, null=True)),
                ('toWardType', models.CharField(max_length=30, null=True)),
                ('fromBedId', models.CharField(max_length=30, null=True)),
                ('toBedId', models.CharField(max_length=30, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('condition', models.IntegerField()),
                ('daysexpected', models.DateField()),
                ('lastverifiedward', models.CharField(max_length=30, null=True)),
                ('patientId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedapp.Patient', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserDeviceMapping',
            fields=[
                ('userId', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('deviceId', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='checkup',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedapp.Patient'),
        ),
        migrations.AddField(
            model_name='checkup',
            name='patientmovementid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bedapp.Movement'),
        ),
        migrations.AddField(
            model_name='bedinfo',
            name='patientId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='bedapp.Patient'),
        ),
    ]
