# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-02 21:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedapp', '0003_auto_20171003_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rollback',
            name='fromWard',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rollback',
            name='fromWardType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rollback',
            name='toWard',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='rollback',
            name='toWardType',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='transfertable',
            name='condition',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='transfertable',
            name='toWard',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
