# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-29 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bedapp', '0004_auto_20171003_0243'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='retainstatus',
            field=models.CharField(default='NO', max_length=10),
        ),
        migrations.AddField(
            model_name='transfertable',
            name='retainstatus',
            field=models.CharField(default='NO', max_length=10),
        ),
        migrations.AlterField(
            model_name='bedinfo',
            name='status',
            field=models.IntegerField(choices=[(0, 'notbooked'), (1, 'partialbooked'), (2, 'booked'), (3, 'retained')], default='notbooked'),
        ),
    ]
